version: '3'

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
    - protoc dashboard.proto --go_out=gen --go_opt=paths=source_relative --go-grpc_out=gen --go-grpc_opt=paths=source_relative
  types:
    cmds: 
    - grpc_tools_node_protoc --js_out=import_style=commonjs,binary:./src/grpc/proto --grpc_out=./src/grpc/proto --plugin=protoc-gen-grpc=./node_modules/.bin/grpc_tools_node_protoc_plugin -I ./proto dashboard.proto

# protoc dashboard.proto --plugin="protoc-gen-ts=./node_modules/.bin/protoc-gen-ts" --js_out="import_style=commonjs,binary:." --ts_out="service=grpc-web:."

# protoc --js_out="import_style=commonjs,binary:." --ts_out="service=grpc-web, mode=grpc-js:." --grpc_out="grpc_js:." dashboard.proto